# config.yaml (estratto rilevante)
# ... (altre sezioni)

ml_model:
  training_days: 90 
  random_forest_n_estimators: 100
  # Semplificato: l'orizzonte di predizione è sempre in giorni,
  # perché il modello ML principale userà sempre dati giornalieri.
  prediction_target_horizon_days: 3 
  
  # La vecchia sezione prediction_horizons per intervallo può essere rimossa o commentata:
  # prediction_horizons:
  #   "1H": 6   
  #   "4H": 3   
  #   "1D_D": 3 
  #   "1D_W": 3 
  #   "1D_M": 3 
  #   "1D_Y": 3 
  # default_prediction_horizon_periods: 3 # Non più necessario se abbiamo solo _days

  min_days_for_indicators_and_training: 200 # Giorni di storico GIORNALIERO per ML/TA
  feature_columns_for_training: ['MA20', 'MA50', 'RSI', 'StochRSI_K', 'StochRSI_D', 'WilliamsR', 'Momentum_ROC10', 'ADX', 'MACD_line', 'Bollinger_High', 'Bollinger_Low', 'Volume_SMA20'] # Esempio di feature da usare

  use_google_ai_studio: false
  google_ai_studio_url_secret_name: "GOOGLE_AI_STUDIO_URL"
  google_ai_studio_token_secret_name: "GOOGLE_AI_STUDIO_TOKEN"

# ... (resto del file config.yaml)
